// GET https://api.spotify.com/v1/browse/new-releases
// TODO: When this gets implemented for real, this should be cached for X hours
import type { NextApiRequest, NextApiResponse } from "next";
import { NewReleases } from "../../shared/types";

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<NewReleases>
) {
  res.status(200).json(new_releases);
}

const new_releases: NewReleases = {
  albums: {
    href: "https://api.spotify.com/v1/browse/new-releases?country=CA&offset=0&limit=20",
    items: [
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0iEtIxbK0KxaSlF7G42ZOp",
            },
            href: "https://api.spotify.com/v1/artists/0iEtIxbK0KxaSlF7G42ZOp",
            id: "0iEtIxbK0KxaSlF7G42ZOp",
            name: "Metro Boomin",
            type: "artist",
            uri: "spotify:artist:0iEtIxbK0KxaSlF7G42ZOp",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/4gR3h0hcpE1iJH0v5bVv78",
        },
        href: "https://api.spotify.com/v1/albums/4gR3h0hcpE1iJH0v5bVv78",
        id: "4gR3h0hcpE1iJH0v5bVv78",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273d93a35654cb16dc6a1b56228",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02d93a35654cb16dc6a1b56228",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851d93a35654cb16dc6a1b56228",
            width: 64,
          },
        ],
        name: "HEROES & VILLAINS",
        release_date: "2022-12-02",
        release_date_precision: "day",
        total_tracks: 15,
        type: "album",
        uri: "spotify:album:4gR3h0hcpE1iJH0v5bVv78",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4GNC7GD6oZMSxPGyXy4MNB",
            },
            href: "https://api.spotify.com/v1/artists/4GNC7GD6oZMSxPGyXy4MNB",
            id: "4GNC7GD6oZMSxPGyXy4MNB",
            name: "Lewis Capaldi",
            type: "artist",
            uri: "spotify:artist:4GNC7GD6oZMSxPGyXy4MNB",
          },
        ],
        available_markets: [
          "AE",
          "AM",
          "AU",
          "AZ",
          "BD",
          "BG",
          "BH",
          "BI",
          "BN",
          "BT",
          "BW",
          "CY",
          "DJ",
          "EE",
          "EG",
          "FI",
          "FJ",
          "FM",
          "GE",
          "GR",
          "HK",
          "ID",
          "IL",
          "IN",
          "IQ",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LK",
          "LS",
          "LT",
          "LV",
          "LY",
          "MD",
          "MG",
          "MH",
          "MN",
          "MO",
          "MU",
          "MV",
          "MW",
          "MY",
          "MZ",
          "NA",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PG",
          "PH",
          "PK",
          "PS",
          "PW",
          "QA",
          "RO",
          "RW",
          "SA",
          "SB",
          "SC",
          "SG",
          "SZ",
          "TH",
          "TJ",
          "TL",
          "TO",
          "TR",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UZ",
          "VN",
          "VU",
          "WS",
          "ZA",
          "ZM",
          "ZW",
          "AD",
          "AL",
          "AO",
          "AT",
          "BA",
          "BE",
          "BJ",
          "CD",
          "CG",
          "CH",
          "CM",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "GA",
          "GQ",
          "HR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "ME",
          "MK",
          "MT",
          "NE",
          "NG",
          "NL",
          "NO",
          "PL",
          "RS",
          "SE",
          "SI",
          "SK",
          "SM",
          "TD",
          "TN",
          "XK",
          "BF",
          "CI",
          "GB",
          "GH",
          "GM",
          "GN",
          "GW",
          "IE",
          "IS",
          "LR",
          "ML",
          "MR",
          "PT",
          "SL",
          "SN",
          "ST",
          "TG",
          "CV",
          "AR",
          "BR",
          "CL",
          "PY",
          "SR",
          "UY",
          "AG",
          "BB",
          "BO",
          "CW",
          "DM",
          "DO",
          "GD",
          "GY",
          "KN",
          "LC",
          "TT",
          "VC",
          "VE",
          "BS",
          "CA",
          "CO",
          "EC",
          "HT",
          "JM",
          "PA",
          "PE",
          "US",
          "BZ",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/7DA9v7969Er1YXEb0z41E7",
        },
        href: "https://api.spotify.com/v1/albums/7DA9v7969Er1YXEb0z41E7",
        id: "7DA9v7969Er1YXEb0z41E7",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273b850aa3be53c301f39325f17",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02b850aa3be53c301f39325f17",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851b850aa3be53c301f39325f17",
            width: 64,
          },
        ],
        name: "Pointless",
        release_date: "2022-12-02",
        release_date_precision: "day",
        total_tracks: 2,
        type: "album",
        uri: "spotify:album:7DA9v7969Er1YXEb0z41E7",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/1VPmR4DJC1PlOtd0IADAO0",
            },
            href: "https://api.spotify.com/v1/artists/1VPmR4DJC1PlOtd0IADAO0",
            id: "1VPmR4DJC1PlOtd0IADAO0",
            name: "$uicideboy$",
            type: "artist",
            uri: "spotify:artist:1VPmR4DJC1PlOtd0IADAO0",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4OYIkXBBN6ET96coWyWAXh",
            },
            href: "https://api.spotify.com/v1/artists/4OYIkXBBN6ET96coWyWAXh",
            id: "4OYIkXBBN6ET96coWyWAXh",
            name: "Germ",
            type: "artist",
            uri: "spotify:artist:4OYIkXBBN6ET96coWyWAXh",
          },
        ],
        available_markets: [
          "AE",
          "AM",
          "AU",
          "AZ",
          "BD",
          "BG",
          "BH",
          "BI",
          "BN",
          "BT",
          "BW",
          "BY",
          "CY",
          "DJ",
          "EE",
          "EG",
          "FI",
          "FJ",
          "FM",
          "GE",
          "GR",
          "HK",
          "ID",
          "IL",
          "IN",
          "IQ",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LK",
          "LS",
          "LT",
          "LV",
          "LY",
          "MD",
          "MG",
          "MH",
          "MN",
          "MO",
          "MU",
          "MV",
          "MW",
          "MY",
          "MZ",
          "NA",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PG",
          "PH",
          "PK",
          "PS",
          "PW",
          "QA",
          "RO",
          "RW",
          "SA",
          "SB",
          "SC",
          "SG",
          "SZ",
          "TH",
          "TJ",
          "TL",
          "TO",
          "TR",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UZ",
          "VN",
          "VU",
          "WS",
          "ZA",
          "ZM",
          "ZW",
          "AD",
          "AL",
          "AO",
          "AT",
          "BA",
          "BE",
          "BJ",
          "CD",
          "CG",
          "CH",
          "CM",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "GA",
          "GQ",
          "HR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "ME",
          "MK",
          "MT",
          "NE",
          "NG",
          "NL",
          "NO",
          "PL",
          "RS",
          "SE",
          "SI",
          "SK",
          "SM",
          "TD",
          "TN",
          "XK",
          "BF",
          "CI",
          "GB",
          "GH",
          "GM",
          "GN",
          "GW",
          "IE",
          "IS",
          "LR",
          "ML",
          "MR",
          "PT",
          "SL",
          "SN",
          "ST",
          "TG",
          "CV",
          "AR",
          "BR",
          "CL",
          "PY",
          "SR",
          "UY",
          "AG",
          "BB",
          "BO",
          "CW",
          "DM",
          "DO",
          "GD",
          "GY",
          "KN",
          "LC",
          "TT",
          "VC",
          "VE",
          "BS",
          "CA",
          "CO",
          "EC",
          "HT",
          "JM",
          "PA",
          "PE",
          "US",
          "BZ",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/48J35hJTQeahYPNJ7t4Q0B",
        },
        href: "https://api.spotify.com/v1/albums/48J35hJTQeahYPNJ7t4Q0B",
        id: "48J35hJTQeahYPNJ7t4Q0B",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273c4463a48907d1fc3c65f5325",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02c4463a48907d1fc3c65f5325",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851c4463a48907d1fc3c65f5325",
            width: 64,
          },
        ],
        name: "My Swisher Sweet, But My Sig Sauer",
        release_date: "2022-12-02",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:48J35hJTQeahYPNJ7t4Q0B",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/2ye2Wgw4gimLv2eAKyk1NB",
            },
            href: "https://api.spotify.com/v1/artists/2ye2Wgw4gimLv2eAKyk1NB",
            id: "2ye2Wgw4gimLv2eAKyk1NB",
            name: "Metallica",
            type: "artist",
            uri: "spotify:artist:2ye2Wgw4gimLv2eAKyk1NB",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/4nQohOCgjIAlnRmqUVYaSv",
        },
        href: "https://api.spotify.com/v1/albums/4nQohOCgjIAlnRmqUVYaSv",
        id: "4nQohOCgjIAlnRmqUVYaSv",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273e79f40ea18f4738b8e910b27",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02e79f40ea18f4738b8e910b27",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851e79f40ea18f4738b8e910b27",
            width: 64,
          },
        ],
        name: "Lux Æterna",
        release_date: "2022-11-28",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:4nQohOCgjIAlnRmqUVYaSv",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5zixe6AbgXPqt4c1uSl94L",
            },
            href: "https://api.spotify.com/v1/artists/5zixe6AbgXPqt4c1uSl94L",
            id: "5zixe6AbgXPqt4c1uSl94L",
            name: "Connor Price",
            type: "artist",
            uri: "spotify:artist:5zixe6AbgXPqt4c1uSl94L",
          },
        ],
        available_markets: [
          "AE",
          "AM",
          "AU",
          "AZ",
          "BD",
          "BG",
          "BH",
          "BI",
          "BN",
          "BT",
          "BW",
          "BY",
          "CY",
          "DJ",
          "EE",
          "EG",
          "FI",
          "FJ",
          "FM",
          "GE",
          "GR",
          "HK",
          "ID",
          "IL",
          "IN",
          "IQ",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LK",
          "LS",
          "LT",
          "LV",
          "LY",
          "MD",
          "MG",
          "MH",
          "MN",
          "MO",
          "MU",
          "MV",
          "MW",
          "MY",
          "MZ",
          "NA",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PG",
          "PH",
          "PK",
          "PS",
          "PW",
          "QA",
          "RO",
          "RW",
          "SA",
          "SB",
          "SC",
          "SG",
          "SZ",
          "TH",
          "TJ",
          "TL",
          "TO",
          "TR",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UZ",
          "VN",
          "VU",
          "WS",
          "ZA",
          "ZM",
          "ZW",
          "AD",
          "AL",
          "AO",
          "AT",
          "BA",
          "BE",
          "BJ",
          "CD",
          "CG",
          "CH",
          "CM",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "GA",
          "GQ",
          "HR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "ME",
          "MK",
          "MT",
          "NE",
          "NG",
          "NL",
          "NO",
          "PL",
          "RS",
          "SE",
          "SI",
          "SK",
          "SM",
          "TD",
          "TN",
          "XK",
          "BF",
          "CI",
          "GB",
          "GH",
          "GM",
          "GN",
          "GW",
          "IE",
          "IS",
          "LR",
          "ML",
          "MR",
          "PT",
          "SL",
          "SN",
          "ST",
          "TG",
          "CV",
          "AR",
          "BR",
          "CL",
          "PY",
          "SR",
          "UY",
          "AG",
          "BB",
          "BO",
          "CW",
          "DM",
          "DO",
          "GD",
          "GY",
          "KN",
          "LC",
          "TT",
          "VC",
          "VE",
          "BS",
          "CA",
          "CO",
          "EC",
          "HT",
          "JM",
          "PA",
          "PE",
          "US",
          "BZ",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/55HYWfQQTWzwrFffFIltvv",
        },
        href: "https://api.spotify.com/v1/albums/55HYWfQQTWzwrFffFIltvv",
        id: "55HYWfQQTWzwrFffFIltvv",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273fcc92a3c5042618923f6c367",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02fcc92a3c5042618923f6c367",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851fcc92a3c5042618923f6c367",
            width: 64,
          },
        ],
        name: "Chatter",
        release_date: "2022-12-02",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:55HYWfQQTWzwrFffFIltvv",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/78rUTD7y6Cy67W1RVzYs7t",
            },
            href: "https://api.spotify.com/v1/artists/78rUTD7y6Cy67W1RVzYs7t",
            id: "78rUTD7y6Cy67W1RVzYs7t",
            name: "PinkPantheress",
            type: "artist",
            uri: "spotify:artist:78rUTD7y6Cy67W1RVzYs7t",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/5Kdlc7Kds94W7UFFg6Me0N",
        },
        href: "https://api.spotify.com/v1/albums/5Kdlc7Kds94W7UFFg6Me0N",
        id: "5Kdlc7Kds94W7UFFg6Me0N",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2735911dc1602a9d100ebe955fc",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e025911dc1602a9d100ebe955fc",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048515911dc1602a9d100ebe955fc",
            width: 64,
          },
        ],
        name: "Boy's a liar",
        release_date: "2022-11-30",
        release_date_precision: "day",
        total_tracks: 2,
        type: "album",
        uri: "spotify:album:5Kdlc7Kds94W7UFFg6Me0N",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6t1gpxYbY8OlLA7D2RiikQ",
            },
            href: "https://api.spotify.com/v1/artists/6t1gpxYbY8OlLA7D2RiikQ",
            id: "6t1gpxYbY8OlLA7D2RiikQ",
            name: "Loud Luxury",
            type: "artist",
            uri: "spotify:artist:6t1gpxYbY8OlLA7D2RiikQ",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3iN9k8uvm4WrgdlOigOH8D",
            },
            href: "https://api.spotify.com/v1/artists/3iN9k8uvm4WrgdlOigOH8D",
            id: "3iN9k8uvm4WrgdlOigOH8D",
            name: "Hook N Sling",
            type: "artist",
            uri: "spotify:artist:3iN9k8uvm4WrgdlOigOH8D",
          },
        ],
        available_markets: ["CA"],
        external_urls: {
          spotify: "https://open.spotify.com/album/4mooz6mCqDSKrb5BzE8sCM",
        },
        href: "https://api.spotify.com/v1/albums/4mooz6mCqDSKrb5BzE8sCM",
        id: "4mooz6mCqDSKrb5BzE8sCM",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273fdd79eb52d9c86672ac8bf1d",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02fdd79eb52d9c86672ac8bf1d",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851fdd79eb52d9c86672ac8bf1d",
            width: 64,
          },
        ],
        name: "Afterparty",
        release_date: "2022-12-02",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:4mooz6mCqDSKrb5BzE8sCM",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/06vEAqcicwoSBw85e8biJx",
            },
            href: "https://api.spotify.com/v1/artists/06vEAqcicwoSBw85e8biJx",
            id: "06vEAqcicwoSBw85e8biJx",
            name: "Rêve",
            type: "artist",
            uri: "spotify:artist:06vEAqcicwoSBw85e8biJx",
          },
        ],
        available_markets: [
          "AE",
          "AM",
          "AU",
          "AZ",
          "BD",
          "BG",
          "BH",
          "BI",
          "BN",
          "BT",
          "BW",
          "CY",
          "DJ",
          "EE",
          "EG",
          "FI",
          "FJ",
          "FM",
          "GE",
          "GR",
          "HK",
          "ID",
          "IL",
          "IN",
          "IQ",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LK",
          "LS",
          "LT",
          "LV",
          "LY",
          "MD",
          "MG",
          "MH",
          "MN",
          "MO",
          "MU",
          "MV",
          "MW",
          "MY",
          "MZ",
          "NA",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PG",
          "PH",
          "PK",
          "PS",
          "PW",
          "QA",
          "RO",
          "RW",
          "SA",
          "SB",
          "SC",
          "SG",
          "SZ",
          "TH",
          "TJ",
          "TL",
          "TO",
          "TR",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UZ",
          "VN",
          "VU",
          "WS",
          "ZA",
          "ZM",
          "ZW",
          "AD",
          "AL",
          "AO",
          "AT",
          "BA",
          "BE",
          "BJ",
          "CD",
          "CG",
          "CH",
          "CM",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "GA",
          "GQ",
          "HR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "ME",
          "MK",
          "MT",
          "NE",
          "NG",
          "NL",
          "NO",
          "PL",
          "RS",
          "SE",
          "SI",
          "SK",
          "SM",
          "TD",
          "TN",
          "XK",
          "BF",
          "CI",
          "GB",
          "GH",
          "GM",
          "GN",
          "GW",
          "IE",
          "IS",
          "LR",
          "ML",
          "MR",
          "PT",
          "SL",
          "SN",
          "ST",
          "TG",
          "CV",
          "AR",
          "BR",
          "CL",
          "PY",
          "SR",
          "UY",
          "AG",
          "BB",
          "BO",
          "CW",
          "DM",
          "DO",
          "GD",
          "GY",
          "KN",
          "LC",
          "TT",
          "VC",
          "VE",
          "BS",
          "CA",
          "CO",
          "EC",
          "HT",
          "JM",
          "PA",
          "PE",
          "US",
          "BZ",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/4Tvc60Tmm2H1gqVJFgkK92",
        },
        href: "https://api.spotify.com/v1/albums/4Tvc60Tmm2H1gqVJFgkK92",
        id: "4Tvc60Tmm2H1gqVJFgkK92",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273111598953777c39a4fbee732",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02111598953777c39a4fbee732",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851111598953777c39a4fbee732",
            width: 64,
          },
        ],
        name: "Hypersexual",
        release_date: "2022-12-02",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:4Tvc60Tmm2H1gqVJFgkK92",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/13ubrt8QOOCPljQ2FL1Kca",
            },
            href: "https://api.spotify.com/v1/artists/13ubrt8QOOCPljQ2FL1Kca",
            id: "13ubrt8QOOCPljQ2FL1Kca",
            name: "A$AP Rocky",
            type: "artist",
            uri: "spotify:artist:13ubrt8QOOCPljQ2FL1Kca",
          },
        ],
        available_markets: [
          "AE",
          "AM",
          "AU",
          "AZ",
          "BD",
          "BG",
          "BH",
          "BI",
          "BN",
          "BT",
          "BW",
          "BY",
          "CY",
          "DJ",
          "EE",
          "EG",
          "FI",
          "FJ",
          "FM",
          "GE",
          "GR",
          "HK",
          "ID",
          "IL",
          "IN",
          "IQ",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LK",
          "LS",
          "LT",
          "LV",
          "LY",
          "MD",
          "MG",
          "MH",
          "MN",
          "MO",
          "MU",
          "MV",
          "MW",
          "MY",
          "MZ",
          "NA",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PG",
          "PH",
          "PK",
          "PS",
          "PW",
          "QA",
          "RO",
          "RW",
          "SA",
          "SB",
          "SC",
          "SG",
          "SZ",
          "TH",
          "TJ",
          "TL",
          "TO",
          "TR",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UZ",
          "VN",
          "VU",
          "WS",
          "ZA",
          "ZM",
          "ZW",
          "AD",
          "AL",
          "AO",
          "AT",
          "BA",
          "BE",
          "BJ",
          "CD",
          "CG",
          "CH",
          "CM",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "GA",
          "GQ",
          "HR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "ME",
          "MK",
          "MT",
          "NE",
          "NG",
          "NL",
          "NO",
          "PL",
          "RS",
          "SE",
          "SI",
          "SK",
          "SM",
          "TD",
          "TN",
          "XK",
          "BF",
          "CI",
          "GB",
          "GH",
          "GM",
          "GN",
          "GW",
          "IE",
          "IS",
          "LR",
          "ML",
          "MR",
          "PT",
          "SL",
          "SN",
          "ST",
          "TG",
          "CV",
          "AR",
          "BR",
          "CL",
          "PY",
          "SR",
          "UY",
          "AG",
          "BB",
          "BO",
          "CW",
          "DM",
          "DO",
          "GD",
          "GY",
          "KN",
          "LC",
          "TT",
          "VC",
          "VE",
          "BS",
          "CA",
          "CO",
          "EC",
          "HT",
          "JM",
          "PA",
          "PE",
          "US",
          "BZ",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3M1sz7dBtyfa1KqdiAylC6",
        },
        href: "https://api.spotify.com/v1/albums/3M1sz7dBtyfa1KqdiAylC6",
        id: "3M1sz7dBtyfa1KqdiAylC6",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2734f49feab905a8faa10faf3ff",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e024f49feab905a8faa10faf3ff",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048514f49feab905a8faa10faf3ff",
            width: 64,
          },
        ],
        name: "Shittin' Me",
        release_date: "2022-12-02",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:3M1sz7dBtyfa1KqdiAylC6",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4oUHIQIBe0LHzYfvXNW4QM",
            },
            href: "https://api.spotify.com/v1/artists/4oUHIQIBe0LHzYfvXNW4QM",
            id: "4oUHIQIBe0LHzYfvXNW4QM",
            name: "Morgan Wallen",
            type: "artist",
            uri: "spotify:artist:4oUHIQIBe0LHzYfvXNW4QM",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/04VpyPCr9PQRWRRp1ecOs1",
        },
        href: "https://api.spotify.com/v1/albums/04VpyPCr9PQRWRRp1ecOs1",
        id: "04VpyPCr9PQRWRRp1ecOs1",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2738a4778fcdf78ed210d12dd21",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e028a4778fcdf78ed210d12dd21",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048518a4778fcdf78ed210d12dd21",
            width: 64,
          },
        ],
        name: "One Thing At A Time (Sampler)",
        release_date: "2022-12-02",
        release_date_precision: "day",
        total_tracks: 3,
        type: "album",
        uri: "spotify:album:04VpyPCr9PQRWRRp1ecOs1",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/20qISvAhX20dpIbOOzGK3q",
            },
            href: "https://api.spotify.com/v1/artists/20qISvAhX20dpIbOOzGK3q",
            id: "20qISvAhX20dpIbOOzGK3q",
            name: "Nas",
            type: "artist",
            uri: "spotify:artist:20qISvAhX20dpIbOOzGK3q",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/1URnnhqYAYcrqrcwql10ft",
            },
            href: "https://api.spotify.com/v1/artists/1URnnhqYAYcrqrcwql10ft",
            id: "1URnnhqYAYcrqrcwql10ft",
            name: "21 Savage",
            type: "artist",
            uri: "spotify:artist:1URnnhqYAYcrqrcwql10ft",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/2K2es8pRFX0kOaEdXZZgMl",
        },
        href: "https://api.spotify.com/v1/albums/2K2es8pRFX0kOaEdXZZgMl",
        id: "2K2es8pRFX0kOaEdXZZgMl",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273bc34741d70d23f4f20d4a2a5",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02bc34741d70d23f4f20d4a2a5",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851bc34741d70d23f4f20d4a2a5",
            width: 64,
          },
        ],
        name: "One Mic, One Gun",
        release_date: "2022-11-29",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:2K2es8pRFX0kOaEdXZZgMl",
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6bmlMHgSheBauioMgKv2tn",
            },
            href: "https://api.spotify.com/v1/artists/6bmlMHgSheBauioMgKv2tn",
            id: "6bmlMHgSheBauioMgKv2tn",
            name: "Powfu",
            type: "artist",
            uri: "spotify:artist:6bmlMHgSheBauioMgKv2tn",
          },
        ],
        available_markets: [
          "AE",
          "AM",
          "AU",
          "AZ",
          "BD",
          "BG",
          "BH",
          "BI",
          "BN",
          "BT",
          "BW",
          "BY",
          "CY",
          "DJ",
          "EE",
          "EG",
          "FI",
          "FJ",
          "FM",
          "GE",
          "GR",
          "HK",
          "ID",
          "IL",
          "IN",
          "IQ",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LK",
          "LS",
          "LT",
          "LV",
          "LY",
          "MD",
          "MG",
          "MH",
          "MN",
          "MO",
          "MU",
          "MV",
          "MW",
          "MY",
          "MZ",
          "NA",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PG",
          "PH",
          "PK",
          "PS",
          "PW",
          "QA",
          "RO",
          "RW",
          "SA",
          "SB",
          "SC",
          "SG",
          "SZ",
          "TH",
          "TJ",
          "TL",
          "TO",
          "TR",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UZ",
          "VN",
          "VU",
          "WS",
          "ZA",
          "ZM",
          "ZW",
          "AD",
          "AL",
          "AO",
          "AT",
          "BA",
          "BE",
          "BJ",
          "CD",
          "CG",
          "CH",
          "CM",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "GA",
          "GQ",
          "HR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "ME",
          "MK",
          "MT",
          "NE",
          "NG",
          "NL",
          "NO",
          "PL",
          "RS",
          "SE",
          "SI",
          "SK",
          "SM",
          "TD",
          "TN",
          "XK",
          "BF",
          "CI",
          "GB",
          "GH",
          "GM",
          "GN",
          "GW",
          "IE",
          "IS",
          "LR",
          "ML",
          "MR",
          "PT",
          "SL",
          "SN",
          "ST",
          "TG",
          "CV",
          "AR",
          "BR",
          "CL",
          "PY",
          "SR",
          "UY",
          "AG",
          "BB",
          "BO",
          "CW",
          "DM",
          "DO",
          "GD",
          "GY",
          "KN",
          "LC",
          "TT",
          "VC",
          "VE",
          "BS",
          "CA",
          "CO",
          "EC",
          "HT",
          "JM",
          "PA",
          "PE",
          "US",
          "BZ",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/5iFPxq21dVb6E7RFjBSYvG",
        },
        href: "https://api.spotify.com/v1/albums/5iFPxq21dVb6E7RFjBSYvG",
        id: "5iFPxq21dVb6E7RFjBSYvG",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b27369eb9e4ca17a974ed9c1833d",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e0269eb9e4ca17a974ed9c1833d",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d0000485169eb9e4ca17a974ed9c1833d",
            width: 64,
          },
        ],
        name: "surrounded by hounds and serpents",
        release_date: "2022-12-02",
        release_date_precision: "day",
        total_tracks: 9,
        type: "album",
        uri: "spotify:album:5iFPxq21dVb6E7RFjBSYvG",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6vclJnUiJ9D7IW0OP54MFT",
            },
            href: "https://api.spotify.com/v1/artists/6vclJnUiJ9D7IW0OP54MFT",
            id: "6vclJnUiJ9D7IW0OP54MFT",
            name: "Fredz",
            type: "artist",
            uri: "spotify:artist:6vclJnUiJ9D7IW0OP54MFT",
          },
        ],
        available_markets: ["AD", "BE", "CH", "FR", "MC"],
        external_urls: {
          spotify: "https://open.spotify.com/album/76k9k3QdqdYkyXuIwKfXgN",
        },
        href: "https://api.spotify.com/v1/albums/76k9k3QdqdYkyXuIwKfXgN",
        id: "76k9k3QdqdYkyXuIwKfXgN",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2739494510be667ecc2297fb1ee",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e029494510be667ecc2297fb1ee",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048519494510be667ecc2297fb1ee",
            width: 64,
          },
        ],
        name: "Spotify Singles",
        release_date: "2022-11-30",
        release_date_precision: "day",
        total_tracks: 2,
        type: "album",
        uri: "spotify:album:76k9k3QdqdYkyXuIwKfXgN",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3MdXrJWsbVzdn6fe5JYkSQ",
            },
            href: "https://api.spotify.com/v1/artists/3MdXrJWsbVzdn6fe5JYkSQ",
            id: "3MdXrJWsbVzdn6fe5JYkSQ",
            name: "Latto",
            type: "artist",
            uri: "spotify:artist:3MdXrJWsbVzdn6fe5JYkSQ",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3ppZNqihWOzuH4A0f4KmeP",
            },
            href: "https://api.spotify.com/v1/artists/3ppZNqihWOzuH4A0f4KmeP",
            id: "3ppZNqihWOzuH4A0f4KmeP",
            name: "Gangsta Boo",
            type: "artist",
            uri: "spotify:artist:3ppZNqihWOzuH4A0f4KmeP",
          },
        ],
        available_markets: [
          "AE",
          "AM",
          "AU",
          "AZ",
          "BD",
          "BG",
          "BH",
          "BI",
          "BN",
          "BT",
          "BW",
          "BY",
          "CY",
          "DJ",
          "EE",
          "EG",
          "FI",
          "FJ",
          "FM",
          "GE",
          "GR",
          "HK",
          "ID",
          "IL",
          "IN",
          "IQ",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LK",
          "LS",
          "LT",
          "LV",
          "LY",
          "MD",
          "MG",
          "MH",
          "MN",
          "MO",
          "MU",
          "MV",
          "MW",
          "MY",
          "MZ",
          "NA",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PG",
          "PH",
          "PK",
          "PS",
          "PW",
          "QA",
          "RO",
          "RW",
          "SA",
          "SB",
          "SC",
          "SG",
          "SZ",
          "TH",
          "TJ",
          "TL",
          "TO",
          "TR",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UZ",
          "VN",
          "VU",
          "WS",
          "ZA",
          "ZM",
          "ZW",
          "AD",
          "AL",
          "AO",
          "AT",
          "BA",
          "BE",
          "BJ",
          "CD",
          "CG",
          "CH",
          "CM",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "GA",
          "GQ",
          "HR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "ME",
          "MK",
          "MT",
          "NE",
          "NG",
          "NL",
          "NO",
          "PL",
          "RS",
          "SE",
          "SI",
          "SK",
          "SM",
          "TD",
          "TN",
          "XK",
          "BF",
          "CI",
          "GB",
          "GH",
          "GM",
          "GN",
          "GW",
          "IE",
          "IS",
          "LR",
          "ML",
          "MR",
          "PT",
          "SL",
          "SN",
          "ST",
          "TG",
          "CV",
          "AR",
          "BR",
          "CL",
          "PY",
          "SR",
          "UY",
          "AG",
          "BB",
          "BO",
          "CW",
          "DM",
          "DO",
          "GD",
          "GY",
          "KN",
          "LC",
          "TT",
          "VC",
          "VE",
          "BS",
          "CA",
          "CO",
          "EC",
          "HT",
          "JM",
          "PA",
          "PE",
          "US",
          "BZ",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/5MnLj1SQmw3nr7oTbJgtuB",
        },
        href: "https://api.spotify.com/v1/albums/5MnLj1SQmw3nr7oTbJgtuB",
        id: "5MnLj1SQmw3nr7oTbJgtuB",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b27337df84cf0611962781f24516",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e0237df84cf0611962781f24516",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d0000485137df84cf0611962781f24516",
            width: 64,
          },
        ],
        name: "FTCU (feat. GloRilla & Gangsta Boo)",
        release_date: "2022-12-02",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:5MnLj1SQmw3nr7oTbJgtuB",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6ydoSd3N2mwgwBHtF6K7eX",
            },
            href: "https://api.spotify.com/v1/artists/6ydoSd3N2mwgwBHtF6K7eX",
            id: "6ydoSd3N2mwgwBHtF6K7eX",
            name: "Calum Scott",
            type: "artist",
            uri: "spotify:artist:6ydoSd3N2mwgwBHtF6K7eX",
          },
        ],
        available_markets: [
          "AE",
          "AM",
          "AU",
          "AZ",
          "BD",
          "BG",
          "BH",
          "BI",
          "BN",
          "BT",
          "BW",
          "CY",
          "DJ",
          "EE",
          "EG",
          "FI",
          "FJ",
          "FM",
          "GE",
          "GR",
          "HK",
          "ID",
          "IL",
          "IN",
          "IQ",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LK",
          "LS",
          "LT",
          "LV",
          "LY",
          "MD",
          "MG",
          "MH",
          "MN",
          "MO",
          "MU",
          "MV",
          "MW",
          "MY",
          "MZ",
          "NA",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PG",
          "PH",
          "PK",
          "PS",
          "PW",
          "QA",
          "RO",
          "RW",
          "SA",
          "SB",
          "SC",
          "SG",
          "SZ",
          "TH",
          "TJ",
          "TL",
          "TO",
          "TR",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UZ",
          "VN",
          "VU",
          "WS",
          "ZA",
          "ZM",
          "ZW",
          "AD",
          "AL",
          "AO",
          "AT",
          "BA",
          "BE",
          "BJ",
          "CD",
          "CG",
          "CH",
          "CM",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "GA",
          "GQ",
          "HR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "ME",
          "MK",
          "MT",
          "NE",
          "NG",
          "NL",
          "NO",
          "PL",
          "RS",
          "SE",
          "SI",
          "SK",
          "SM",
          "TD",
          "TN",
          "XK",
          "BF",
          "CI",
          "GB",
          "GH",
          "GM",
          "GN",
          "GW",
          "IE",
          "IS",
          "LR",
          "ML",
          "MR",
          "PT",
          "SL",
          "SN",
          "ST",
          "TG",
          "CV",
          "AR",
          "BR",
          "CL",
          "PY",
          "SR",
          "UY",
          "AG",
          "BB",
          "BO",
          "CW",
          "DM",
          "DO",
          "GD",
          "GY",
          "KN",
          "LC",
          "TT",
          "VC",
          "VE",
          "BS",
          "CA",
          "CO",
          "EC",
          "HT",
          "JM",
          "PA",
          "PE",
          "US",
          "BZ",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3RekhTEhQfdXOKlOAgjJiO",
        },
        href: "https://api.spotify.com/v1/albums/3RekhTEhQfdXOKlOAgjJiO",
        id: "3RekhTEhQfdXOKlOAgjJiO",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273dcfe03a2d64b565192a2cca2",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02dcfe03a2d64b565192a2cca2",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851dcfe03a2d64b565192a2cca2",
            width: 64,
          },
        ],
        name: "One More Try",
        release_date: "2022-12-02",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:3RekhTEhQfdXOKlOAgjJiO",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0gSAxSvAApQc71cTpoXDFu",
            },
            href: "https://api.spotify.com/v1/artists/0gSAxSvAApQc71cTpoXDFu",
            id: "0gSAxSvAApQc71cTpoXDFu",
            name: "Tenille Arts",
            type: "artist",
            uri: "spotify:artist:0gSAxSvAApQc71cTpoXDFu",
          },
        ],
        available_markets: [
          "AE",
          "AM",
          "AU",
          "AZ",
          "BD",
          "BG",
          "BH",
          "BI",
          "BN",
          "BT",
          "BW",
          "BY",
          "CY",
          "DJ",
          "EE",
          "EG",
          "FI",
          "FJ",
          "FM",
          "GE",
          "GR",
          "HK",
          "ID",
          "IL",
          "IN",
          "IQ",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LK",
          "LS",
          "LT",
          "LV",
          "LY",
          "MD",
          "MG",
          "MH",
          "MN",
          "MO",
          "MU",
          "MV",
          "MW",
          "MY",
          "MZ",
          "NA",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PG",
          "PH",
          "PK",
          "PS",
          "PW",
          "QA",
          "RO",
          "RW",
          "SA",
          "SB",
          "SC",
          "SG",
          "SZ",
          "TH",
          "TJ",
          "TL",
          "TO",
          "TR",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UZ",
          "VN",
          "VU",
          "WS",
          "ZA",
          "ZM",
          "ZW",
          "AD",
          "AL",
          "AO",
          "AT",
          "BA",
          "BE",
          "BJ",
          "CD",
          "CG",
          "CH",
          "CM",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "GA",
          "GQ",
          "HR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "ME",
          "MK",
          "MT",
          "NE",
          "NG",
          "NL",
          "NO",
          "PL",
          "RS",
          "SE",
          "SI",
          "SK",
          "SM",
          "TD",
          "TN",
          "XK",
          "BF",
          "CI",
          "GB",
          "GH",
          "GM",
          "GN",
          "GW",
          "IE",
          "IS",
          "LR",
          "ML",
          "MR",
          "PT",
          "SL",
          "SN",
          "ST",
          "TG",
          "CV",
          "AR",
          "BR",
          "CL",
          "PY",
          "SR",
          "UY",
          "AG",
          "BB",
          "BO",
          "CW",
          "DM",
          "DO",
          "GD",
          "GY",
          "KN",
          "LC",
          "TT",
          "VC",
          "VE",
          "BS",
          "CA",
          "CO",
          "EC",
          "HT",
          "JM",
          "PA",
          "PE",
          "US",
          "BZ",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6Pbmoox4o7GVCyQDkgOWaX",
        },
        href: "https://api.spotify.com/v1/albums/6Pbmoox4o7GVCyQDkgOWaX",
        id: "6Pbmoox4o7GVCyQDkgOWaX",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2730a05e7eb3ca469adbb8ad96e",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e020a05e7eb3ca469adbb8ad96e",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048510a05e7eb3ca469adbb8ad96e",
            width: 64,
          },
        ],
        name: "Motel On the Moon",
        release_date: "2022-12-02",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:6Pbmoox4o7GVCyQDkgOWaX",
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0z4gvV4rjIZ9wHck67ucSV",
            },
            href: "https://api.spotify.com/v1/artists/0z4gvV4rjIZ9wHck67ucSV",
            id: "0z4gvV4rjIZ9wHck67ucSV",
            name: "Akon",
            type: "artist",
            uri: "spotify:artist:0z4gvV4rjIZ9wHck67ucSV",
          },
        ],
        available_markets: [
          "AE",
          "AM",
          "AU",
          "AZ",
          "BD",
          "BG",
          "BH",
          "BI",
          "BN",
          "BT",
          "BW",
          "BY",
          "CY",
          "DJ",
          "EE",
          "EG",
          "FI",
          "FJ",
          "FM",
          "GE",
          "GR",
          "HK",
          "ID",
          "IL",
          "IN",
          "IQ",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LK",
          "LS",
          "LT",
          "LV",
          "LY",
          "MD",
          "MG",
          "MH",
          "MN",
          "MO",
          "MU",
          "MV",
          "MW",
          "MY",
          "MZ",
          "NA",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PG",
          "PH",
          "PK",
          "PS",
          "PW",
          "QA",
          "RO",
          "RW",
          "SA",
          "SB",
          "SC",
          "SG",
          "SZ",
          "TH",
          "TJ",
          "TL",
          "TO",
          "TR",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UZ",
          "VN",
          "VU",
          "WS",
          "ZA",
          "ZM",
          "ZW",
          "AD",
          "AL",
          "AO",
          "AT",
          "BA",
          "BE",
          "BJ",
          "CD",
          "CG",
          "CH",
          "CM",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "GA",
          "GQ",
          "HR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "ME",
          "MK",
          "MT",
          "NE",
          "NG",
          "NL",
          "NO",
          "PL",
          "RS",
          "SE",
          "SI",
          "SK",
          "SM",
          "TD",
          "TN",
          "XK",
          "BF",
          "CI",
          "GB",
          "GH",
          "GM",
          "GN",
          "GW",
          "IE",
          "IS",
          "LR",
          "ML",
          "MR",
          "PT",
          "SL",
          "SN",
          "ST",
          "TG",
          "CV",
          "AR",
          "BR",
          "CL",
          "PY",
          "SR",
          "UY",
          "AG",
          "BB",
          "BO",
          "CW",
          "DM",
          "DO",
          "GD",
          "GY",
          "KN",
          "LC",
          "TT",
          "VC",
          "VE",
          "BS",
          "CA",
          "CO",
          "EC",
          "HT",
          "JM",
          "PA",
          "PE",
          "US",
          "BZ",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/2bWREa0DSY6RC9dkEAzGAL",
        },
        href: "https://api.spotify.com/v1/albums/2bWREa0DSY6RC9dkEAzGAL",
        id: "2bWREa0DSY6RC9dkEAzGAL",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273071141b5da0ee2474c7dba30",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02071141b5da0ee2474c7dba30",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851071141b5da0ee2474c7dba30",
            width: 64,
          },
        ],
        name: "TT Freak",
        release_date: "2022-12-02",
        release_date_precision: "day",
        total_tracks: 7,
        type: "album",
        uri: "spotify:album:2bWREa0DSY6RC9dkEAzGAL",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5R1cUyk9ysrruOo4ErpGjg",
            },
            href: "https://api.spotify.com/v1/artists/5R1cUyk9ysrruOo4ErpGjg",
            id: "5R1cUyk9ysrruOo4ErpGjg",
            name: "LU KALA",
            type: "artist",
            uri: "spotify:artist:5R1cUyk9ysrruOo4ErpGjg",
          },
        ],
        available_markets: [
          "AE",
          "AM",
          "AU",
          "AZ",
          "BD",
          "BG",
          "BH",
          "BI",
          "BN",
          "BT",
          "BW",
          "BY",
          "CY",
          "DJ",
          "EE",
          "EG",
          "FI",
          "FJ",
          "FM",
          "GE",
          "GR",
          "HK",
          "ID",
          "IL",
          "IN",
          "IQ",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LK",
          "LS",
          "LT",
          "LV",
          "LY",
          "MD",
          "MG",
          "MH",
          "MN",
          "MO",
          "MU",
          "MV",
          "MW",
          "MY",
          "MZ",
          "NA",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PG",
          "PH",
          "PK",
          "PS",
          "PW",
          "QA",
          "RO",
          "RW",
          "SA",
          "SB",
          "SC",
          "SG",
          "SZ",
          "TH",
          "TJ",
          "TL",
          "TO",
          "TR",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UZ",
          "VN",
          "VU",
          "WS",
          "ZA",
          "ZM",
          "ZW",
          "AD",
          "AL",
          "AO",
          "AT",
          "BA",
          "BE",
          "BJ",
          "CD",
          "CG",
          "CH",
          "CM",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "GA",
          "GQ",
          "HR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "ME",
          "MK",
          "MT",
          "NE",
          "NG",
          "NL",
          "NO",
          "PL",
          "RS",
          "SE",
          "SI",
          "SK",
          "SM",
          "TD",
          "TN",
          "XK",
          "BF",
          "CI",
          "GB",
          "GH",
          "GM",
          "GN",
          "GW",
          "IE",
          "IS",
          "LR",
          "ML",
          "MR",
          "PT",
          "SL",
          "SN",
          "ST",
          "TG",
          "CV",
          "AR",
          "BR",
          "CL",
          "PY",
          "SR",
          "UY",
          "AG",
          "BB",
          "BO",
          "CW",
          "DM",
          "DO",
          "GD",
          "GY",
          "KN",
          "LC",
          "TT",
          "VC",
          "VE",
          "BS",
          "CA",
          "CO",
          "EC",
          "HT",
          "JM",
          "PA",
          "PE",
          "US",
          "BZ",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6G32ymoo3YjIUKVMGIKJUY",
        },
        href: "https://api.spotify.com/v1/albums/6G32ymoo3YjIUKVMGIKJUY",
        id: "6G32ymoo3YjIUKVMGIKJUY",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b27380934206f5f61394e9ddaf53",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e0280934206f5f61394e9ddaf53",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d0000485180934206f5f61394e9ddaf53",
            width: 64,
          },
        ],
        name: "Pretty Girl Era",
        release_date: "2022-12-02",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:6G32ymoo3YjIUKVMGIKJUY",
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6tPHARSq45lQ8BSALCfkFC",
            },
            href: "https://api.spotify.com/v1/artists/6tPHARSq45lQ8BSALCfkFC",
            id: "6tPHARSq45lQ8BSALCfkFC",
            name: "Lainey Wilson",
            type: "artist",
            uri: "spotify:artist:6tPHARSq45lQ8BSALCfkFC",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/7MQhqC96gC1il14HCHbfr9",
        },
        href: "https://api.spotify.com/v1/albums/7MQhqC96gC1il14HCHbfr9",
        id: "7MQhqC96gC1il14HCHbfr9",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273231167e3d308863f7d42f2fc",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02231167e3d308863f7d42f2fc",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851231167e3d308863f7d42f2fc",
            width: 64,
          },
        ],
        name: "Bell Bottom Country",
        release_date: "2022-11-28",
        release_date_precision: "day",
        total_tracks: 16,
        type: "album",
        uri: "spotify:album:7MQhqC96gC1il14HCHbfr9",
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/16T3el1CEjX49qFA7UT2n5",
            },
            href: "https://api.spotify.com/v1/artists/16T3el1CEjX49qFA7UT2n5",
            id: "16T3el1CEjX49qFA7UT2n5",
            name: "Snotty Nose Rez Kids",
            type: "artist",
            uri: "spotify:artist:16T3el1CEjX49qFA7UT2n5",
          },
        ],
        available_markets: ["AU", "NZ"],
        external_urls: {
          spotify: "https://open.spotify.com/album/5zErQTgiVZNE5SpR1Pw2Ae",
        },
        href: "https://api.spotify.com/v1/albums/5zErQTgiVZNE5SpR1Pw2Ae",
        id: "5zErQTgiVZNE5SpR1Pw2Ae",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273a268c17135b06e11b92eff83",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02a268c17135b06e11b92eff83",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851a268c17135b06e11b92eff83",
            width: 64,
          },
        ],
        name: "I'M GOOD, HBU?",
        release_date: "2022-12-02",
        release_date_precision: "day",
        total_tracks: 8,
        type: "album",
        uri: "spotify:album:5zErQTgiVZNE5SpR1Pw2Ae",
      },
    ],
    limit: 20,
    next: "https://api.spotify.com/v1/browse/new-releases?country=CA&offset=20&limit=20",
    offset: 0,
    previous: null,
    total: 100,
  },
};
